<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8"/>
	<title>DumboPHP Console</title>
	<?=stylesheet_link_tag('adminlayout.css');?>
	<!--[if lt IE 9]>
	<?=stylesheet_link_tag('ie.css');?>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<?=javascript_include_tag(array('jquery-1.6.4','functions'));?>
</head>
<body>
	<header id="header">
		<hgroup>
			<h1 class="site_title"><a href="index.html">DumboPHP Admin</a></h1>
			<h2 class="section_title"><?=$this->title;?></h2>
		</hgroup>
	</header> <!-- end of header bar -->
	<?=$this->content;?>
</body>
</html>